# Generated by Django 5.2.6 on 2025-12-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('product_id', models.CharField(max_length=20, verbose_name='商品ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('quantity', models.IntegerField(verbose_name='数量')),
            ],
        ),
    ]
